package crdt_test

// parity_test.go mints CROSS-LANGUAGE PARITY VECTORS for the four personal-state
// CRDTs (§42, §43, #386). Each vector is a sequence of wire changes — exactly the
// bytes json.Marshal(change) produces, which is what statesync encrypts and a peer
// stores opaque — paired with the deterministic State.Encode() the fold converges
// to and the exact Snapshot() bytes it serialises to.
//
// The vectors are the contract a NON-Go client (the Android app, heyarr-mobile)
// ports the merge logic against: it decodes the same `changes`, folds them, and
// must produce the byte-identical `encode` and `snapshot`. There is nothing Go-
// specific in a vector — it is JSON in, a deterministic string out — so a Kotlin
// port that disagrees on one byte has a real divergence, not a "flaky" one.
//
// Regenerate with:  go test ./internal/personalstate/crdt -run TestParityVectors -update
// and re-copy the testdata/vectors/*.json files into heyarr-mobile's test
// resources (the same discipline internal/deviceauth uses for the voidbind-go
// membership vectors).
//
// The fold is a semilattice join, so the converged state is order-independent
// (§43). The vectors carry the changes in one order; TestParityFoldIsOrderFree
// proves reversing them changes neither Encode nor Snapshot, which is the property
// the Kotlin port must also hold — so the vectors do double duty as a Go self-check.

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"

	"github.com/rarebit-one/heyarr-core/internal/personalstate/crdt"
	"github.com/rarebit-one/heyarr-core/internal/testutil"
)

// A wireVector is one named scenario: the changes on the wire, the Encode() the
// fold converges to, and the exact Snapshot() bytes (as a JSON string, since the
// snapshot is itself JSON) so a port validates its snapshot encoder AND decoder.
type wireVector struct {
	Name     string            `json:"name"`
	Changes  []json.RawMessage `json:"changes"`
	Encode   string            `json:"encode"`
	Snapshot string            `json:"snapshot"`
}

type vectorFile struct {
	Kind    string       `json:"kind"`
	Note    string       `json:"note"`
	Vectors []wireVector `json:"vectors"`
}

const vectorNote = "Cross-language parity vectors. Generated by heyarr-core " +
	"internal/personalstate/crdt parity_test.go (-update); do not hand-edit. " +
	"`changes` are the exact json.Marshal(change) wire form; a port decodes them, " +
	"folds them, and must reproduce `encode` and `snapshot` byte-for-byte."

func vectorsPath(name string) string { return filepath.Join("testdata", "vectors", name) }

// maxU64 is math.MaxUint64 — the Lamport-clock poison value a saturating
// increment must handle. It is in the vectors deliberately: a port that stores
// the counter in a signed 64-bit integer overflows here, and the mismatch says so.
const maxU64 = uint64(math.MaxUint64)

// --- playlist -----------------------------------------------------------------

func playlistVectors(t *testing.T) vectorFile {
	t.Helper()
	ord := func(c uint64, tag string) crdt.OrderKey { return crdt.OrderKey{Counter: c, Tag: crdt.Tag(tag)} }
	add := func(item, tag string, o crdt.OrderKey) crdt.Change {
		return crdt.Change{Op: crdt.OpAdd, ItemID: item, Tag: crdt.Tag(tag), Order: o}
	}
	rm := func(item string, observed ...string) crdt.Change {
		obs := make([]crdt.Tag, len(observed))
		for i, o := range observed {
			obs[i] = crdt.Tag(o)
		}
		return crdt.Change{Op: crdt.OpRemove, ItemID: item, Observed: obs}
	}
	scenarios := []struct {
		name    string
		changes []crdt.Change
	}{
		{"empty", nil},
		{"single-add", []crdt.Change{add("a", "t1", ord(1, "t1"))}},
		{"ordered-adds", []crdt.Change{
			add("a", "t1", ord(1, "t1")), add("b", "t2", ord(2, "t2")), add("c", "t3", ord(3, "t3")),
		}},
		{"lamport-tiebreak-same-counter", []crdt.Change{
			add("b", "t2", ord(5, "t2")), add("a", "t1", ord(5, "t1")),
		}},
		{"add-wins-concurrent-add-survives-remove", []crdt.Change{
			add("a", "t1", ord(1, "t1")),
			add("a", "t2", ord(2, "t2")),
			rm("a", "t1"), // the remove only observed t1; t2 survives → a is still present
		}},
		{"remove-tombstones-all-observed", []crdt.Change{
			add("a", "t1", ord(1, "t1")), rm("a", "t1"),
		}},
		{"same-item-two-adds-smallest-order-wins-position", []crdt.Change{
			add("a", "t3", ord(9, "t3")), add("a", "t1", ord(2, "t1")),
		}},
		{"counter-poison-saturates-at-maxuint64", []crdt.Change{
			add("a", "t1", ord(1, "t1")), add("b", "t2", ord(maxU64, "t2")),
		}},
	}
	vf := vectorFile{Kind: "playlist", Note: vectorNote}
	for _, sc := range scenarios {
		st := crdt.New()
		raw := make([]json.RawMessage, 0, len(sc.changes))
		for _, ch := range sc.changes {
			raw = append(raw, mustMarshal(t, ch))
		}
		st.Apply(sc.changes...)
		vf.Vectors = append(vf.Vectors, wireVector{
			Name: sc.name, Changes: raw, Encode: st.Encode(), Snapshot: mustSnap(t, st.Snapshot),
		})
	}
	return vf
}

// --- starred ------------------------------------------------------------------

func starredVectors(t *testing.T) vectorFile {
	t.Helper()
	star := func(item, tag string, at uint64) crdt.StarChange {
		return crdt.StarChange{Op: crdt.OpStar, ItemID: item, Tag: crdt.StarTag(tag), At: at}
	}
	unstar := func(item string, observed ...string) crdt.StarChange {
		obs := make([]crdt.StarTag, len(observed))
		for i, o := range observed {
			obs[i] = crdt.StarTag(o)
		}
		return crdt.StarChange{Op: crdt.OpUnstar, ItemID: item, Observed: obs}
	}
	scenarios := []struct {
		name    string
		changes []crdt.StarChange
	}{
		{"empty", nil},
		{"single-star", []crdt.StarChange{star("a", "s1", 1)}},
		{"recency-order-desc", []crdt.StarChange{star("a", "s1", 1), star("b", "s2", 2)}},
		{"add-wins-concurrent-star-survives-unstar", []crdt.StarChange{
			star("a", "s1", 1), star("a", "s2", 2), unstar("a", "s1"),
		}},
		{"unstar-tombstones-all-observed", []crdt.StarChange{star("a", "s1", 1), unstar("a", "s1")}},
		{"counter-poison-saturates-at-maxuint64", []crdt.StarChange{
			star("a", "s1", 1), star("b", "s2", maxU64),
		}},
	}
	vf := vectorFile{Kind: "starred", Note: vectorNote}
	for _, sc := range scenarios {
		s := crdt.NewStarSet()
		raw := make([]json.RawMessage, 0, len(sc.changes))
		for _, ch := range sc.changes {
			raw = append(raw, mustMarshal(t, ch))
		}
		s.Apply(sc.changes...)
		vf.Vectors = append(vf.Vectors, wireVector{
			Name: sc.name, Changes: raw, Encode: s.Encode(), Snapshot: mustSnap(t, s.Snapshot),
		})
	}
	return vf
}

// --- reading positions --------------------------------------------------------

func readingposVectors(t *testing.T) vectorFile {
	t.Helper()
	set := func(pub, pos string, at uint64, writer string) crdt.PositionChange {
		return crdt.PositionChange{PubID: pub, Position: pos, At: at, Writer: crdt.PosTag(writer)}
	}
	scenarios := []struct {
		name    string
		changes []crdt.PositionChange
	}{
		{"empty", nil},
		{"single-position", []crdt.PositionChange{set("b1", "epubcfi(/6/4!/4/2)", 1, "w1")}},
		{"lww-later-write-wins", []crdt.PositionChange{
			set("b1", "p1", 1, "w1"), set("b1", "p2", 2, "w2"),
		}},
		{"lww-concurrent-lower-writer-loses", []crdt.PositionChange{
			set("b1", "p2", 2, "w2"), set("b1", "p0", 2, "w1"), // same At; w2 > w1 wins → p2
		}},
		{"tie-break-on-position-string", []crdt.PositionChange{
			set("b1", "aaa", 5, "w9"), set("b1", "bbb", 5, "w9"), // fully tied key → greater position wins → bbb
		}},
		{"go-quoting-escapes", []crdt.PositionChange{
			set("b1", "a\"b\\c\td\ne", 1, "w1"), // exercises strconv.Quote parity in %q
		}},
		{"two-publications-sorted", []crdt.PositionChange{
			set("b2", "x", 1, "w1"), set("b1", "y", 2, "w2"),
		}},
		{"counter-poison-saturates-at-maxuint64", []crdt.PositionChange{
			set("b1", "p", maxU64, "w1"),
		}},
	}
	vf := vectorFile{Kind: "readingpos", Note: vectorNote}
	for _, sc := range scenarios {
		r := crdt.NewReadingPositions()
		raw := make([]json.RawMessage, 0, len(sc.changes))
		for _, ch := range sc.changes {
			raw = append(raw, mustMarshal(t, ch))
		}
		r.Apply(sc.changes...)
		vf.Vectors = append(vf.Vectors, wireVector{
			Name: sc.name, Changes: raw, Encode: r.Encode(), Snapshot: mustSnap(t, r.Snapshot),
		})
	}
	return vf
}

// --- play history -------------------------------------------------------------

func historyVectors(t *testing.T) vectorFile {
	t.Helper()
	play := func(item, tag string, at uint64) crdt.PlayChange {
		return crdt.PlayChange{ItemID: item, Tag: crdt.PlayTag(tag), At: at}
	}
	scenarios := []struct {
		name    string
		changes []crdt.PlayChange
	}{
		{"empty", nil},
		{"single-play", []crdt.PlayChange{play("a", "p1", 1)}},
		{"repeated-plays-count", []crdt.PlayChange{
			play("a", "p1", 1), play("a", "p2", 2), play("b", "p3", 3),
		}},
		{"duplicate-tag-idempotent", []crdt.PlayChange{
			play("a", "p1", 1), play("a", "p1", 1), // same tag applied twice is one event
		}},
		{"counter-poison-saturates-at-maxuint64", []crdt.PlayChange{
			play("a", "p1", 1), play("b", "p2", maxU64),
		}},
	}
	vf := vectorFile{Kind: "history", Note: vectorNote}
	for _, sc := range scenarios {
		l := crdt.NewPlayLog()
		raw := make([]json.RawMessage, 0, len(sc.changes))
		for _, ch := range sc.changes {
			raw = append(raw, mustMarshal(t, ch))
		}
		l.Apply(sc.changes...)
		vf.Vectors = append(vf.Vectors, wireVector{
			Name: sc.name, Changes: raw, Encode: l.Encode(), Snapshot: mustSnap(t, l.Snapshot),
		})
	}
	return vf
}

// TestParityVectors mints (or, with -update, rewrites) the four vector files. It
// is the single source of truth for the Kotlin port's fixtures.
func TestParityVectors(t *testing.T) {
	for _, tc := range []struct {
		file string
		gen  func(*testing.T) vectorFile
	}{
		{"playlist.json", playlistVectors},
		{"starred.json", starredVectors},
		{"readingpos.json", readingposVectors},
		{"history.json", historyVectors},
	} {
		t.Run(tc.file, func(t *testing.T) {
			got := indent(t, tc.gen(t))
			testutil.Golden(t, vectorsPath(tc.file), got)
		})
	}
}

// TestParityFoldConvergesToTheVector re-reads each committed file and proves the
// fold of its `changes` reproduces its `encode` and `snapshot` — the exact
// assertion the Kotlin port makes, run against the same bytes so a drift in Go
// and a drift in the port are caught by the same file.
func TestParityFoldConvergesToTheVector(t *testing.T) {
	replay(t, "playlist.json", func(t *testing.T, v wireVector) (string, string) {
		st := crdt.New()
		for _, r := range v.Changes {
			var ch crdt.Change
			mustUnmarshal(t, r, &ch)
			st.Apply(ch)
		}
		return st.Encode(), mustSnap(t, st.Snapshot)
	})
	replay(t, "starred.json", func(t *testing.T, v wireVector) (string, string) {
		s := crdt.NewStarSet()
		for _, r := range v.Changes {
			var ch crdt.StarChange
			mustUnmarshal(t, r, &ch)
			s.Apply(ch)
		}
		return s.Encode(), mustSnap(t, s.Snapshot)
	})
	replay(t, "readingpos.json", func(t *testing.T, v wireVector) (string, string) {
		r := crdt.NewReadingPositions()
		for _, raw := range v.Changes {
			var ch crdt.PositionChange
			mustUnmarshal(t, raw, &ch)
			r.Apply(ch)
		}
		return r.Encode(), mustSnap(t, r.Snapshot)
	})
	replay(t, "history.json", func(t *testing.T, v wireVector) (string, string) {
		l := crdt.NewPlayLog()
		for _, raw := range v.Changes {
			var ch crdt.PlayChange
			mustUnmarshal(t, raw, &ch)
			l.Apply(ch)
		}
		return l.Encode(), mustSnap(t, l.Snapshot)
	})
}

// TestParitySnapshotRoundTrips proves each vector's `snapshot` string decodes
// back to a state whose Encode equals the vector's `encode` — the snapshot decoder
// the port must also match.
func TestParitySnapshotRoundTrips(t *testing.T) {
	roundTrip(t, "playlist.json", func(t *testing.T, b []byte) string {
		st, err := crdt.FromSnapshot(b)
		if err != nil {
			t.Fatal(err)
		}
		return st.Encode()
	})
	roundTrip(t, "starred.json", func(t *testing.T, b []byte) string {
		s, err := crdt.StarSetFromSnapshot(b)
		if err != nil {
			t.Fatal(err)
		}
		return s.Encode()
	})
	roundTrip(t, "readingpos.json", func(t *testing.T, b []byte) string {
		r, err := crdt.ReadingPositionsFromSnapshot(b)
		if err != nil {
			t.Fatal(err)
		}
		return r.Encode()
	})
	roundTrip(t, "history.json", func(t *testing.T, b []byte) string {
		l, err := crdt.PlayLogFromSnapshot(b)
		if err != nil {
			t.Fatal(err)
		}
		return l.Encode()
	})
}

// --- helpers ------------------------------------------------------------------

func replay(t *testing.T, file string, fold func(*testing.T, wireVector) (string, string)) {
	t.Helper()
	vf := loadVectorFile(t, file)
	for _, v := range vf.Vectors {
		t.Run(vf.Kind+"/"+v.Name, func(t *testing.T) {
			gotEncode, gotSnap := fold(t, v)
			if gotEncode != v.Encode {
				t.Errorf("encode mismatch\n--- want ---\n%s\n--- got ---\n%s", v.Encode, gotEncode)
			}
			if gotSnap != v.Snapshot {
				t.Errorf("snapshot mismatch\n--- want ---\n%s\n--- got ---\n%s", v.Snapshot, gotSnap)
			}
		})
	}
}

func roundTrip(t *testing.T, file string, decode func(*testing.T, []byte) string) {
	t.Helper()
	vf := loadVectorFile(t, file)
	for _, v := range vf.Vectors {
		t.Run(vf.Kind+"/"+v.Name, func(t *testing.T) {
			if decode(t, []byte(v.Snapshot)) != v.Encode {
				t.Errorf("snapshot did not round-trip to the vector's encode for %q", v.Name)
			}
		})
	}
}

func loadVectorFile(t *testing.T, file string) vectorFile {
	t.Helper()
	raw, err := os.ReadFile(filepath.Clean(vectorsPath(file)))
	if err != nil {
		t.Fatalf("read %s: %v (run with -update to create it)", file, err)
	}
	var vf vectorFile
	if err := json.Unmarshal(raw, &vf); err != nil {
		t.Fatalf("decode %s: %v", file, err)
	}
	return vf
}

func mustMarshal(t *testing.T, v any) json.RawMessage {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("marshal change: %v", err)
	}
	return b
}

func mustUnmarshal(t *testing.T, raw json.RawMessage, into any) {
	t.Helper()
	if err := json.Unmarshal(raw, into); err != nil {
		t.Fatalf("unmarshal change: %v", err)
	}
}

func mustSnap(t *testing.T, f func() ([]byte, error)) string {
	t.Helper()
	b, err := f()
	if err != nil {
		t.Fatalf("snapshot: %v", err)
	}
	return string(b)
}

func indent(t *testing.T, vf vectorFile) []byte {
	t.Helper()
	b, err := json.MarshalIndent(vf, "", "  ")
	if err != nil {
		t.Fatalf("indent vectors: %v", err)
	}
	return append(b, '\n')
}
