package protocol_test

// parity_test.go mints CROSS-LANGUAGE PARITY VECTORS for the content-addressed
// change id and snapshot id (change.go / snapshot.go). The id is a length-framed
// BLAKE3 digest over the space, the (canonicalised) parents and the ciphertext
// (§42, §44, Invariant 1) — the node re-derives it and refuses a mismatch, so a
// non-Go client (heyarr-mobile) that mints a change MUST compute the byte-identical
// id or every write it makes is rejected.
//
// Each vector is opaque bytes in, a "blake3:<hex>" id out. The `parents` /
// `frontier` are given in a DELIBERATELY non-canonical order (unsorted, with a
// duplicate and an empty string) so a port's canonicalisation — sort, de-dup,
// drop empty — is exercised, not just the hash. There is nothing Go-specific in a
// vector.
//
// Regenerate with:  go test ./internal/personalstate/protocol -run TestIDParityVectors -update
// and re-copy testdata/vectors/changeid.json into heyarr-mobile's test resources.

import (
	"encoding/base64"
	"encoding/json"
	"testing"

	"github.com/rarebit-one/heyarr-core/internal/personalstate/protocol"
	"github.com/rarebit-one/heyarr-core/internal/testutil"
)

type changeIDVector struct {
	Name          string   `json:"name"`
	SpaceID       string   `json:"space_id"`
	Parents       []string `json:"parents"`
	CiphertextB64 string   `json:"ciphertext_b64"`
	ChangeID      string   `json:"change_id"`
}

type snapshotIDVector struct {
	Name          string   `json:"name"`
	SpaceID       string   `json:"space_id"`
	Frontier      []string `json:"frontier"`
	CiphertextB64 string   `json:"ciphertext_b64"`
	SnapshotID    string   `json:"snapshot_id"`
}

type idVectorFile struct {
	Note      string             `json:"note"`
	Changes   []changeIDVector   `json:"changes"`
	Snapshots []snapshotIDVector `json:"snapshots"`
}

const idNote = "Cross-language parity vectors for the content-addressed change/snapshot id " +
	"(length-framed BLAKE3, domains heyarr/personalstate/change/v1 and .../snapshot/v1). " +
	"Generated by heyarr-core internal/personalstate/protocol parity_test.go (-update); do not hand-edit. " +
	"`parents`/`frontier` are given non-canonical on purpose; a port must sort, de-dup and drop empties " +
	"before hashing, then reproduce the id byte-for-byte."

func TestIDParityVectors(t *testing.T) {
	ct := func(s string) []byte { return []byte(s) }
	b64 := func(b []byte) string { return base64.StdEncoding.EncodeToString(b) }

	changeInputs := []struct {
		name    string
		space   string
		parents []string
		ct      []byte
	}{
		{"root-no-parents", "space-1", nil, ct("cipher-A")},
		{"single-parent", "space-1", []string{"blake3:aa"}, ct("cipher-B")},
		{"two-parents-already-sorted", "space-1", []string{"blake3:aa", "blake3:bb"}, ct("cipher-C")},
		{"parents-unsorted-dup-and-empty", "space-1", []string{"blake3:bb", "", "blake3:aa", "blake3:bb"}, ct("cipher-C")},
		{"empty-space-segment-is-not-empty-ciphertext", "sp", []string{"blake3:zz"}, ct("\x00\x01\x02binary")},
	}
	var changes []changeIDVector
	for _, in := range changeInputs {
		ec, err := protocol.NewChange(in.space, in.parents, in.ct)
		if err != nil {
			t.Fatalf("%s: NewChange: %v", in.name, err)
		}
		changes = append(changes, changeIDVector{
			Name: in.name, SpaceID: in.space, Parents: in.parents,
			CiphertextB64: b64(in.ct), ChangeID: ec.ChangeID,
		})
	}

	snapInputs := []struct {
		name     string
		space    string
		frontier []string
		ct       []byte
	}{
		{"no-frontier", "space-1", nil, ct("snap-A")},
		{"frontier-unsorted-dup-and-empty", "space-1", []string{"blake3:bb", "blake3:aa", "", "blake3:aa"}, ct("snap-B")},
	}
	var snaps []snapshotIDVector
	for _, in := range snapInputs {
		es, err := protocol.NewSnapshot(in.space, in.frontier, in.ct)
		if err != nil {
			t.Fatalf("%s: NewSnapshot: %v", in.name, err)
		}
		snaps = append(snaps, snapshotIDVector{
			Name: in.name, SpaceID: in.space, Frontier: in.frontier,
			CiphertextB64: b64(in.ct), SnapshotID: es.SnapshotID,
		})
	}

	out := idVectorFile{Note: idNote, Changes: changes, Snapshots: snaps}
	buf, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	testutil.Golden(t, "testdata/vectors/changeid.json", append(buf, '\n'))

	// Re-derive each id through the public constructor and Validate() so the
	// committed file is self-consistent with the code that produced it — the same
	// pair of assertions the Kotlin port makes (compute the id; Validate accepts it).
	for _, v := range changes {
		raw, _ := base64.StdEncoding.DecodeString(v.CiphertextB64)
		ec, err := protocol.NewChange(v.SpaceID, v.Parents, raw)
		if err != nil || ec.ChangeID != v.ChangeID {
			t.Fatalf("change %s: id=%s want %s (err %v)", v.Name, ec.ChangeID, v.ChangeID, err)
		}
		if err := ec.Validate(); err != nil {
			t.Fatalf("change %s: Validate: %v", v.Name, err)
		}
	}
}
