package protocol_test

// snapshot_envelope_test.go pins the authenticated snapshot envelope (#681) and
// mints its CROSS-LANGUAGE PARITY VECTORS. A Kotlin reader (heyarr-kmp) must build
// the byte-identical envelope for a snapshot it seals, and reach the same verdict
// — authenticated, legacy, or refused — for each presented (space, frontier).
//
// Regenerate with:  go test ./internal/personalstate/protocol -run TestSnapshotEnvelopeVectors -update
// and re-copy testdata/vectors/snapshot_envelope.json into heyarr-kmp's test resources.

import (
	"encoding/base64"
	"encoding/json"
	"errors"
	"testing"

	"github.com/rarebit-one/heyarr-core/internal/personalstate/protocol"
	"github.com/rarebit-one/heyarr-core/internal/testutil"
)

type envelopeSealVector struct {
	Name        string   `json:"name"`
	SpaceID     string   `json:"space_id"`
	Frontier    []string `json:"frontier"`
	StateB64    string   `json:"state_b64"`
	EnvelopeB64 string   `json:"envelope_b64"`
}

type envelopeOpenVector struct {
	Name              string   `json:"name"`
	PlaintextB64      string   `json:"plaintext_b64"`
	PresentedSpaceID  string   `json:"presented_space_id"`
	PresentedFrontier []string `json:"presented_frontier"`
	// Verdict is "authenticated", "legacy" or "refused".
	Verdict  string `json:"verdict"`
	StateB64 string `json:"state_b64,omitempty"`
}

type envelopeVectorFile struct {
	Note string               `json:"note"`
	Seal []envelopeSealVector `json:"seal"`
	Open []envelopeOpenVector `json:"open"`
}

const envelopeNote = "Cross-language parity vectors for the authenticated snapshot envelope (#681): " +
	"field(\"heyarr/personalstate/snapshot-envelope/v2\") ‖ field(space) ‖ uvarint(n) ‖ field(head)×n ‖ field(state), " +
	"field(b) = uvarint(len b) ‖ b, heads canonical (sorted, de-duplicated, empties dropped). " +
	"`seal`: a port must build envelope_b64 byte-for-byte. `open`: a port must reach the same verdict for the " +
	"decrypted plaintext presented under (space, frontier) — authenticated, legacy (no envelope) or refused. " +
	"Generated by heyarr-core internal/personalstate/protocol snapshot_envelope_test.go (-update); do not hand-edit."

func TestSnapshotEnvelopeVectors(t *testing.T) {
	b64 := func(b []byte) string { return base64.StdEncoding.EncodeToString(b) }
	playlist := []byte(`{"entries":[]}`)

	sealIn := []struct {
		name     string
		space    string
		frontier []string
		state    []byte
	}{
		{"no-frontier", "space-1", nil, playlist},
		{"frontier-unsorted-dup-and-empty", "space-1", []string{"blake3:bb", "", "blake3:aa", "blake3:bb"}, playlist},
		{"binary-state", "sp", []string{"blake3:zz"}, []byte("\x00\x01\x02binary")},
	}
	var seals []envelopeSealVector
	for _, in := range sealIn {
		seals = append(seals, envelopeSealVector{
			Name: in.name, SpaceID: in.space, Frontier: in.frontier, StateB64: b64(in.state),
			EnvelopeB64: b64(protocol.SealSnapshotPlaintext(in.space, in.frontier, in.state)),
		})
	}

	sealed := protocol.SealSnapshotPlaintext("space-1", []string{"blake3:aa", "blake3:bb"}, playlist)
	withTrailer := append(append([]byte(nil), sealed...), 0x00)
	truncated := sealed[:len(sealed)-3]
	openIn := []struct {
		name     string
		pt       []byte
		space    string
		frontier []string
		verdict  string
	}{
		{"matches", sealed, "space-1", []string{"blake3:aa", "blake3:bb"}, "authenticated"},
		{"matches-non-canonical-spelling", sealed, "space-1", []string{"blake3:bb", "blake3:aa", ""}, "authenticated"},
		{"relabelled-newer-frontier", sealed, "space-1", []string{"blake3:cc"}, "refused"},
		{"relabelled-head-dropped", sealed, "space-1", []string{"blake3:aa"}, "refused"},
		{"relabelled-frontier-emptied", sealed, "space-1", nil, "refused"},
		{"relabelled-space", sealed, "space-2", []string{"blake3:aa", "blake3:bb"}, "refused"},
		{"trailing-bytes", withTrailer, "space-1", []string{"blake3:aa", "blake3:bb"}, "refused"},
		{"truncated", truncated, "space-1", []string{"blake3:aa", "blake3:bb"}, "refused"},
		{"legacy-bare-state", playlist, "space-1", []string{"blake3:anything"}, "legacy"},
	}
	var opens []envelopeOpenVector
	for _, in := range openIn {
		snap := protocol.EncryptedSnapshot{SpaceID: in.space, Frontier: in.frontier}
		state, authed, err := protocol.OpenSnapshotPlaintext(snap, in.pt)
		got := "legacy"
		switch {
		case err != nil:
			got = "refused"
			state = nil
		case authed:
			got = "authenticated"
		}
		if got != in.verdict {
			t.Fatalf("%s: verdict %s (err %v), want %s", in.name, got, err, in.verdict)
		}
		if got == "refused" && !errors.Is(err, protocol.ErrSnapshotBindingMismatch) && !errors.Is(err, protocol.ErrSnapshotEnvelopeMalformed) {
			t.Fatalf("%s: refused with an unexpected error: %v", in.name, err)
		}
		if got != "refused" && string(state) != string(playlist) {
			t.Fatalf("%s: state %q, want %q", in.name, state, playlist)
		}
		v := envelopeOpenVector{
			Name: in.name, PlaintextB64: b64(in.pt), PresentedSpaceID: in.space,
			PresentedFrontier: in.frontier, Verdict: got,
		}
		if state != nil {
			v.StateB64 = b64(state)
		}
		opens = append(opens, v)
	}

	buf, err := json.MarshalIndent(envelopeVectorFile{Note: envelopeNote, Seal: seals, Open: opens}, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	testutil.Golden(t, "testdata/vectors/snapshot_envelope.json", append(buf, '\n'))
}

// TestSnapshotEnvelopeNeverCollidesWithLegacy: every personal-state CRDT
// serialises its snapshot as a JSON object, and the envelope's first byte is the
// length of its domain — never '{'. So a legacy snapshot can never be mistaken for
// an envelope, nor an envelope stripped to look legacy without re-encrypting.
func TestSnapshotEnvelopeNeverCollidesWithLegacy(t *testing.T) {
	env := protocol.SealSnapshotPlaintext("s", nil, []byte("{}"))
	if env[0] == '{' {
		t.Fatalf("the envelope starts with '{' and would read as a legacy snapshot")
	}
}
