// Command genlibrary writes the synthetic library that scripts/acceptance.sh
// drives Heyarr against, and a manifest describing it.
//
// It lives under internal/testutil rather than in cmd/ because it is not part
// of the product: goreleaser builds ./cmd/heyarr and nothing else (ADR-0002 —
// one binary, roles as subcommands), and a second shipped binary that only the
// test harness uses would undermine that. Run it with `go run`.
//
//	go run ./internal/testutil/fixtures/cmd/genlibrary -out /tmp/lib -manifest /tmp/lib.json
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/rarebit-one/heyarr-core/internal/testutil/fixtures"
)

func main() {
	out := flag.String("out", "", "directory to generate the library into (required)")
	manifest := flag.String("manifest", "", "path to write the JSON manifest to (default: none)")
	size := flag.Int64("large-size", fixtures.DefaultLargeFileSize,
		"size in bytes of the streaming fixture; smaller makes the demo faster and the range assertions weaker")
	seed := flag.Uint64("seed", fixtures.DefaultSeed, "seed for the generated bytes")
	flag.Parse()

	if *out == "" {
		fmt.Fprintln(os.Stderr, "genlibrary: -out is required")
		flag.Usage()
		os.Exit(2)
	}

	m, err := fixtures.WriteLibrary(*out, fixtures.Options{LargeFileSize: *size, Seed: *seed})
	if err != nil {
		fmt.Fprintf(os.Stderr, "genlibrary: %v\n", err)
		os.Exit(1)
	}
	if *manifest != "" {
		if err := m.WriteJSON(*manifest); err != nil {
			fmt.Fprintf(os.Stderr, "genlibrary: %v\n", err)
			os.Exit(1)
		}
	}

	fmt.Printf("generated %d files (%d distinct blobs) under %s\n",
		len(m.Files), m.DistinctBlobs, m.Root)
}
