# shellcheck shell=bash
# A section of scripts/acceptance.sh: sourced by it, in order, never run alone.
# ---------------------------------------------------------------------------
# What this demo proves, and what it does not (M3-15)
# ---------------------------------------------------------------------------
#
# Printed rather than filed, because a limitation in a document is one nobody
# reads at the moment it matters. Whoever runs this and sees it pass should see
# the boundary of what passing means in the same breath.
note "what this run proves, and what it does not"
printf '       proven, on this machine, in this run:\n'
printf '         a want for content that existed NOWHERE reached bytes under\n'
printf '         management — searched, evaluated, explained, acquired, verified\n'
printf '         and ingested — with NO REAL INDEXER present (§84, ADR-0026).\n'
printf '         a want that found three releases and accepted none left three\n'
printf '         durable explanations rather than a silence (§63).\n'
printf '         a node with no toolchain, no indexer and no download client\n'
printf '         starts, scans, ingests, serves ranges, and says which of those\n'
printf '         it cannot do (ADR-0023, ADR-0025).\n'
printf '         PLACEMENT, by two peer processes with two data directories, two\n'
printf '         databases, two content stores and two Ed25519 identities, each\n'
printf '         enrolled on the other'"'"'s public key and talking over mutually\n'
printf '         authenticated TLS with no CA anywhere (§26, ADR-0012). A blob\n'
printf '         was deleted from one store — really deleted, from a real disk —\n'
printf '         the OTHER node'"'"'s API reported PLACEMENT_CONVERGING and named the\n'
printf '         peer missing it, the destination pulled the bytes, verified them\n'
printf '         itself and only then claimed the replica, and the same API\n'
printf '         answered FULLY_SATISFIED. Bytes on NEITHER peer answered\n'
printf '         not_satisfied rather than converging, which is the distinction\n'
printf '         §56 draws the state for. The whole arc ran twice: once with each\n'
printf '         node as `heyarr all`, once with each node as three separate role\n'
printf '         processes (ADR-0002).\n'
printf '         THE CONTROLLER CARRIED NO BYTES, asserted from the node that\n'
printf '         SENT them rather than from a counter that stayed still. Node A\n'
printf '         recorded serving this blob on its PEER SURFACE, by GET, to the\n'
printf '         peer whose pinned certificate opened the connection; node B\n'
printf '         pulled the whole blob and re-hashed it itself (§21, §32,\n'
printf '         ADR-0030). Two listeners, two trust roots, and every byte\n'
printf '         accounted for by the one a bearer token cannot open. A\n'
printf '         client-API read of the same blob moments earlier moved the\n'
printf '         client API'"'"'s counter and left the peer surface'"'"'s record empty,\n'
printf '         so the two are known to be distinguishable rather than assumed\n'
printf '         to be.\n'
printf '         GARBAGE COLLECTION REFUSED TO DELETE THE LAST COPY. With the\n'
printf '         second peer stopped and waited for, a blob nothing referenced\n'
printf '         and a one-nanosecond grace window — garbage by every measure the\n'
printf '         first three milestones had — was kept, and reported as spared,\n'
printf '         by hash, naming the peer nothing could be established about\n'
printf '         (ADR-0018). The same collector on the same node unlinked a blob\n'
printf '         minutes earlier, while that node was still a fabric of one, so\n'
printf '         this is a gate and not a collector that refuses everything.\n'
printf '         CHUNK MANIFESTS, AND THE THIRD STATE A BOOLEAN COULD NOT HOLD.\n'
printf '         `blobs.chunked` had been 0 on every row in every deployment\n'
printf '         since Milestone 1 because nothing ever wrote it, and §16 asks a\n'
printf '         question with three answers. All three were read off one\n'
printf '         running fabric in one pass: a blob with a manifest, a blob\n'
printf '         RECORDED as never needing one, and a blob nobody has decided\n'
printf '         about — asserted as an inequality, not inferred from three\n'
printf '         separate reads (§16, ADR-0034). Asking never generated one:\n'
printf '         ten reads of the state left no manifest, no chunk row and no\n'
printf '         chunk_blob job, measured against the job queue rather than\n'
printf '         against the answer.\n'
printf '         LAZY CHUNKING, BY A JOB AND BY NOTHING ELSE. Ingest chunked\n'
printf '         nothing; no sweep chunked anything; the manifests appeared\n'
printf '         when a convergence cycle decided the bytes had to cross a\n'
printf '         network, which is §16'"'"'s own trigger. The blob above the 4 MiB\n'
printf '         threshold got a manifest and the one below it was recorded as\n'
printf '         never needing one — the two sides of the threshold, on the same\n'
printf '         node, in the same pass — and a second cycle changed neither.\n'
printf '         WHICH WORKER CAN DO WHAT, from the running binary rather than\n'
printf '         from a unit test (#112, ADR-0039). The worker this run started\n'
printf '         advertised ITSELF within its startup beat — the assertion no Go\n'
printf '         test can make, because every one of them passes on a build\n'
printf '         where the beat is never started — with an expiry in the future,\n'
printf '         a stated source for every capability, and an exact-match filter\n'
printf '         that answers nothing for a partial dotted segment. A second\n'
printf '         worker against the same database appeared as its own holder, so\n'
printf '         the view is per worker rather than per node.\n'
printf '         A LYING REPLICA ROW, CAUGHT (Refusal 3, ADR-0018, #184). The\n'
printf '         refusal below is the easy half — nothing answered. This is the\n'
printf '         other one: node B was UP and reachable, its row said `present`\n'
printf '         and had been confirmed seconds earlier, its bytes were then\n'
printf '         deleted from its disk without it reporting again, and node A was\n'
printf '         asked to reclaim its last copy. A dialled the peer, B denied\n'
printf '         holding the bytes, the sweep refused by name, and THE ROW WAS\n'
printf '         CORRECTED to `missing` rather than deleted — so the next sweep\n'
printf '         does not rediscover the same lie. Until #184 this path was\n'
printf '         unreachable from a shell: a remote peer'"'"'s health was pinned at\n'
printf '         `unknown` and the sweep refused with `peer_unreachable` before\n'
printf '         it ever asked. Peer health was asserted `unknown` FIRST and then\n'
printf '         observed moving to `reachable` on peer-surface traffic alone,\n'
printf '         with the timestamp an operator acts on beside it.\n'
printf '         A ONE-WAY PAIRING IS REPORTED AND ENROLLED, NEVER REFUSED\n'
printf '         (#186, ADR-0037, ADR-0038). One node was pointed at a port that\n'
printf '         refuses connections so the return leg genuinely could not\n'
printf '         answer; the enrolment SUCCEEDED, and the operator was told which\n'
printf '         direction failed, at which address, that it is not a fault, and\n'
printf '         why. A healthy pairing said nothing at all, which is what makes\n'
printf '         the report worth reading.\n'
printf '         COOPERATIVE ACQUISITION, AS A NUMBER (§23, §24, M6). Two peers\n'
printf '         wanted the same blob and, as far as either catalogue could\n'
printf '         tell, nobody held it — `replicas` has no `partial` state, so a\n'
printf '         peer part-way through a fetch is recorded exactly like one that\n'
printf '         never heard of it. Both took the PIECE path rather than the\n'
printf '         streamed pull, asked every pinned member what it held, fetched\n'
printf '         from several of them at once, and each verified the whole\n'
printf '         object against its own BLAKE3 digest before it became a blob.\n'
printf '         The cooperation claim is an INEQUALITY measured from the\n'
printf '         sending side: the external source served strictly less than the\n'
printf '         two full copies two independent pulls would have cost, and the\n'
printf '         difference crossed directly between the peers. A blob that\n'
printf '         arrived that way then range-read over ordinary HTTP on a bearer\n'
printf '         token, and caused no piece anywhere — measured against a piece\n'
printf '         record that had just moved, so the absence is an absence and\n'
printf '         not an uninstrumented path (§33, §85).\n'
printf '\n'
printf '       NOT proven, and not claimed:\n'
printf '         WHICH WAY THE PEERS HELPED EACH OTHER, or how much. The\n'
printf '         assertion above is that bytes moved between the peers and that\n'
printf '         the external source served less than two copies. It is NOT that\n'
printf '         each peer served the other: measured on this machine, one peer\n'
printf '         ran slightly ahead and seeded the other, and the other seeded\n'
printf '         nothing back. That is a property of two transfers starting at\n'
printf '         the same instant on one kernel, not of the feature, and\n'
printf '         asserting it would be asserting a race. The split between the\n'
printf '         sources is not asserted either, for the reason the repair\n'
printf '         section gives about percentages: read the inequality, and read\n'
printf '         the share as an illustration of it.\n'
printf '         THAT PIECE EXCHANGE IS FASTER. Nothing here measures\n'
printf '         throughput. What is shown is that the external source moved\n'
printf '         fewer bytes, which is the claim §23 makes; whether the wall\n'
printf '         clock improved is a different question and this file does not\n'
printf '         ask it.\n'
printf '         A PEER SERVING FROM A PARTIAL UNDER CONTENTION. Each peer here\n'
printf '         served pieces out of a blob it was still assembling, which is\n'
printf '         the capability that turns a pull into a swarm — but with three\n'
printf '         members on one loopback interface. Nothing has met a peer that\n'
printf '         stalls mid-piece, a partial reaped underneath a reader, or a\n'
printf '         member revoked while it was serving.\n'
printf '         A REAL NETWORK. The two peers above are two PROCESSES ON ONE\n'
printf '         MACHINE. They share a kernel, a disk, a clock and a loopback\n'
printf '         interface. That is enough for the protocol, the pinning, the\n'
printf '         verification, the refusals and the data path, and it is the\n'
printf '         whole of what was shown: nothing in this run has met a\n'
printf '         partition, a slow link, an MTU, packet loss, a reordered or\n'
printf '         half-open connection, or two clocks that disagree. A green run\n'
printf '         here says the fabric is correct, not that it is deployable.\n'
printf '         A GENUINELY ONE-WAY PATH. Two processes on one loopback\n'
printf '         interface reach each other by construction, so the topology\n'
printf '         #186 was found on cannot occur here. The section above\n'
printf '         SIMULATES it, by pointing one node'"'"'s record of the other at a\n'
printf '         port that refuses connections, and proves the report fires and\n'
printf '         names the direction. It says nothing about what a real\n'
printf '         asymmetric path does to a transfer already in flight. Note that\n'
printf '         under ADR-0038 such a pairing is ORDINARY rather than broken:\n'
printf '         each peer is authoritative for its own site, so a node that\n'
printf '         cannot be reached back still serves everything on its own disk\n'
printf '         and still fetches what it lacks from the peer it can reach. The\n'
printf '         cost is convergence in one direction, and nothing here is\n'
printf '         degraded for want of a partner.\n'
printf '         A SECOND PHYSICAL MACHINE, and by extension any deployment\n'
printf '         host. Nothing above left this one. Peer-to-peer mTLS, pinning,\n'
printf '         revocation and re-enrolment WERE exercised between two real\n'
printf '         machines during Milestone 4, and #184'"'"'s liveness transition and\n'
printf '         #186'"'"'s return-path check were exercised between two real\n'
printf '         machines on different subnets during Milestone 5 — by a person,\n'
printf '         at two keyboards, once each. That is recorded here so its\n'
printf '         absence from this run is not mistaken for its absence\n'
printf '         altogether, and it is not an assertion in this file. This\n'
printf '         paragraph describes the run.\n'
printf '         THE PROBED HALF OF PEER LIVENESS. The transition above is\n'
printf '         driven by traffic ARRIVING: node A recorded node B because node\n'
printf '         B spoke to its peer surface. The idle prober — a node dialling a\n'
printf '         peer that has said nothing, over pinned mTLS, to find out\n'
printf '         whether it is still there — is asserted in\n'
printf '         internal/peer/health rather than here, and the two-machine run\n'
printf '         that observed the transition observed the inbound half of it\n'
printf '         too. Nothing in this file moves a health value by probing.\n'
printf '         A REAL INDEXER. No Torznab client has ever answered a search\n'
printf '         here; every candidate above came from a fake, and ADR-0026 says\n'
printf '         that stays true in CI forever. The client now EXISTS — it is\n'
printf '         tested against a corpus captured from two different Torznab\n'
printf '         servers — but no assertion above was answered by one.\n'
printf '         What those two servers do not cover is quality attributes: the\n'
printf '         only tracker safe to capture from into a public repository\n'
printf '         indexes Linux distributions, which assert no resolution, codec\n'
printf '         or audio. Against a real indexer today, this system determines\n'
printf '         a release SIZE and reports every quality rule undetermined.\n'
printf '         TRANSCODE. Milestone 2 ships remux only, and nothing through\n'
printf '         Milestone 5 has needed more: quality profiles select BETWEEN\n'
printf '         releases rather than producing them, and replication moves\n'
printf '         bytes — now fewer of them — without looking inside them.\n'
printf '         LINKED ASSETS still have no blob (ADR-0020). Milestone 3 added a\n'
printf '         fifth place that has to say so — placement, which reports\n'
printf '         not_applicable rather than a vacuous satisfied.\n'
printf '         METADATA. Identification is still Milestone 1'"'"'s path parser, and\n'
printf '         HDR detection is still a substring match on a probe profile.\n'
printf '         THE ARC ITSELF ends at AVAILABLE, not CONTENT_SATISFIED, and\n'
printf '         always will: the artifact it acquires stands in for a completed\n'
printf '         download and is not media, so no toolchain can measure it. That\n'
printf '         is the right answer — a gate that cannot be shown to hold must\n'
printf '         not pass — and measurement against real media is proven by the\n'
printf '         satisfaction section instead.\n'

# The part of "NOT proven" that is a property of THIS MACHINE rather than of
# this milestone (M5-10, #187).
#
# Everything above is a limitation of the system and reads the same on every
# runner. This is different: it is what this particular machine was not equipped
# to ask, and it is the difference between a green run here and a green run on
# the equipped CI runner. Without it the two are indistinguishable, which is how
# five green local runs measured the absence of ffprobe.
if (( CAPS_UNEXERCISED_N > 0 )); then
  printf '         WHAT THIS MACHINE COULD NOT ASK. %d assertion block(s)\n' "$CAPS_UNEXERCISED_N"
  printf '         declared a capability this machine does not have. Their\n'
  printf '         subject was ABSENT, so they were not run — they are neither\n'
  printf '         failures nor coverage, and the branch that ran in their place\n'
  printf '         asserts the degraded behaviour instead (ADR-0023, ADR-0025):\n'
  capability_ledger '           '
  printf '         A green run here is NOT a green run on a machine, or a build,\n'
  printf '         that has them. Two kinds are listed above and they close\n'
  printf '         differently: a MACHINE capability (ffmpeg, ffprobe) closes by\n'
  printf '         installing the pinned toolchain with scripts/toolchain.sh, or\n'
  printf '         by reading CI, which runs it both ways. A BUILD gap — a block\n'
  printf '         whose subject is a code path not on this build — closes only\n'
  printf '         when that path lands, and no amount of tooling here will\n'
  printf '         change it. Each entry says which it is.\n'
else
  printf '         NOTHING WAS LEFT UNASKED for want of a capability: every\n'
  printf '         assertion block in this file found what it declared it needed,\n'
  printf '         so this run is the complete one (#187).\n'
fi
printf '\n'
printf '       NEW IN THIS MILESTONE, and stated rather than left to be found:\n'
printf '         PARTIAL TRANSFER STATE EXISTS NOW, and ADR-0035 is what it had\n'
printf '         to satisfy. Milestone 4 had no partial state at all — a receive\n'
printf '         that did not finish left nothing, and that absence is what made\n'
printf '         the handler idempotent. It is idempotent in a stronger sense\n'
printf '         now: a re-run re-verifies what an earlier attempt left, against\n'
printf '         a manifest this node fetched and checked itself, and keeps only\n'
printf '         the contiguous prefix that checks out. The resume unit is a\n'
printf '         CHUNK and never a byte offset; the assembled result is hashed\n'
printf '         WHOLE before publication; partial bytes are addressable by\n'
printf '         nothing and are never a replica; and a blob with no manifest is\n'
printf '         still not resumable, retried whole, which is §16 doing its job\n'
printf '         rather than a gap.\n'
printf '         WHAT THIS RUN DRIVES OF THAT, AND WHAT IT DOES NOT. The saving\n'
printf '         is asserted above as a number, over mTLS, against a 100%%%%\n'
printf '         control — but by the REPAIR path, because that is the one a\n'
printf '         shell can make deterministic. Resumption after an interruption,\n'
printf '         and reuse across a modified file, are asserted in\n'
printf '         internal/peer/transfer and not here: the first needs a transfer\n'
printf '         interrupted at a chosen point, which from outside means a test\n'
printf '         hook in production code or a race, and the second needs a\n'
printf '         second blob built to share chunks with the first, which moves\n'
printf '         catalogue counts this file asserts elsewhere. A flaky assertion\n'
printf '         about a saving would be worse than this paragraph.\n'
printf '         MANIFESTS ARE LAZY, so any blob may have one, may be recorded as\n'
printf '         never needing one, or may not have been decided about — and the\n'
printf '         third is the ordinary state of a library nothing has replicated.\n'
printf '         This run exercises all three, but it reaches `present` and\n'
printf '         `not_required` only through a convergence cycle on a two-peer\n'
printf '         fabric. A single-node Heyarr stays entirely `undecided` forever,\n'
printf '         which is correct and is asserted above, and it means a\n'
printf '         one-machine deployment exercises none of the chunk paths.\n'
printf '         REPAIR WAS NOT PROVEN AGAINST REAL CORRUPTION. Every damaged\n'
printf '         blob in this repository'"'"'s tests was damaged by OVERWRITING BYTES\n'
printf '         THROUGH THE FILESYSTEM. That is not bit rot, not a failing\n'
printf '         sector, and not a torn write — the three things repair exists\n'
printf '         for — and it is not a filesystem that returns EIO on a read. It\n'
printf '         establishes that the repairer detects a digest mismatch, fetches\n'
printf '         only the chunks that changed, stages a whole replacement, and\n'
printf '         never edits a blob in place (ADR-0036). It establishes nothing\n'
printf '         about the failure modes of a real disk.\n'
printf '         THE SAVINGS ARE DEMONSTRATIONS, NOT BENCHMARKS. Every byte count\n'
printf '         above is measured on a fixture sized to fit a 240-second\n'
printf '         acceptance budget. The ratios are real and the controls are\n'
printf '         real, and a number measured on a few megabytes says nothing\n'
printf '         about a twenty-gigabyte blob over a link that is slower than a\n'
printf '         disk. Nothing here is a performance claim.\n'
printf '         AND THE CLAIM ASSERTED IS THE CHUNK COUNT, not the percentage.\n'
printf '         One chunk fetched out of N is exact and independent of how big\n'
printf '         the fixture is; the percentage is a property of the fixture and\n'
printf '         of the chunker. At the shipped parameters — 256 KiB minimum,\n'
printf '         1 MiB average, 4 MiB maximum — the blob repaired above is about\n'
printf '         ninety chunks, so one of them reads at roughly one per cent. An\n'
printf '         earlier five-megabyte fixture was THREE chunks, where the same\n'
printf '         correct behaviour measured between 8%%%% and 23%%%% depending on\n'
printf '         where a content-defined boundary happened to fall. Nothing about\n'
printf '         the feature changed between those two numbers. Read the\n'
printf '         numerator, and read the percentage as an illustration of it.\n'
printf '         THIS REPOSITORY IS PUBLIC, AND THE GUARD IS NEW. A real host\n'
printf '         name, a document named after a real machine and a personal home\n'
printf '         directory were on `main` when this milestone opened (#211) and\n'
printf '         were scrubbed during it. `make hygiene` now enforces the rule\n'
printf '         rather than trusting it: shape patterns plus retired proper\n'
printf '         nouns held as SHA-256 DIGESTS, so the guard cannot spell what it\n'
printf '         forbids. It found a real device MAC in a renderer fixture on its\n'
printf '         first run, which is the argument for it. A guard is not a proof\n'
printf '         of cleanliness — it catches the shapes somebody thought of.\n'
printf '\n'

# The verdict line. It carries the capability gap, because the verdict line is
# what a person actually reads and what a CI log gets scrolled to — a limitation
# reported only in the middle of 400 `ok`s is one nobody sees at the moment it
# matters (#187).
CAPS_VERDICT=""
if (( CAPS_UNEXERCISED_N > 0 )); then
  CAPS_VERDICT=$(capability_names | tr '\n' ' ' | sed 's/ $//; s/ /, /g')
fi

VERDICT_REACHED=1
if (( FAILED )); then
  printf '\n\033[31macceptance: FAILED\033[0m — %d assertions, %d of them failing\n' \
    "$ASSERTIONS" "${#FAILURES[@]}"
  if (( ${#FAILURES[@]} > 0 )); then
    printf '\n  what failed, in the order it happened:\n'
    local_i=1
    for f in "${FAILURES[@]}"; do
      printf '    %d. %s\n' "$local_i" "$f"
      local_i=$(( local_i + 1 ))
    done
    printf '\n  The FIRST one is usually the cause and the rest its consequences —\n'
    printf '  a wait that never lands runs to its full timeout, so a run that blew\n'
    printf '  its time budget very often blew it BECAUSE of the failure above,\n'
    printf '  not instead of it (#274). Read down, not up.\n'
  fi
  if (( CAPS_MISSING_N > 0 )); then
    printf '  %d of those failures are MISSING CAPABILITIES: an assertion declared\n' "$CAPS_MISSING_N"
    printf '  something this machine does not have, so it could not be exercised.\n'
    printf '  That is a failed run, deliberately — see #187.\n'
  fi
  exit 1
fi
if (( CAPS_UNEXERCISED_N > 0 )); then
  printf '\n\033[32macceptance: all checks passed\033[0m — %d assertions, ' "$ASSERTIONS"
  printf '\033[33m%d block(s) NOT exercised\033[0m (absent: %s)\n' \
    "$CAPS_UNEXERCISED_N" "$CAPS_VERDICT"
  printf '  a green run here is not a green run on a machine that has them (#187)\n'
else
  printf '\n\033[32macceptance: all checks passed\033[0m — %d assertions, every declared capability present\n' \
    "$ASSERTIONS"
fi
