// Package fixtures builds the synthetic library that scripts/acceptance.sh
// drives Heyarr against (M1-18).
//
// Everything is GENERATED rather than committed, for three reasons. Sample
// media carries licensing that an AGPL repository should not have to reason
// about. A ~200 MB streaming fixture cannot live in git at all. And a generated
// tree can report what it built — see Manifest — so the demo asserts against
// what is actually on disk instead of against numbers someone typed into a
// shell script and will forget to update.
//
// Generation is deterministic: the same seed produces byte-identical files, so
// the expected blob hashes are stable and a fixture that changes is a change
// somebody made (ADR-0017).
package fixtures

import (
	"encoding/json"
	"fmt"
	"hash/crc32"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/rarebit-one/heyarr-core/internal/domain/ingest"
	"github.com/rarebit-one/heyarr-core/internal/hashing"
)

// DefaultLargeFileSize is the streaming fixture's size. Large enough that
// range serving is genuinely exercised — a file that fits in one buffer proves
// nothing about a 20 GB remux — and small enough that the demo stays under the
// two minutes M1-18 asks for.
const DefaultLargeFileSize = 200 << 20

// DefaultSeed makes the tree reproducible. Any value works; a fixed one means
// the manifest's hashes are the same on every machine.
const DefaultSeed uint64 = 0x68657961_72726669 // "heyarrfi"

// Options configure the generated library.
type Options struct {
	// LargeFileSize is the size of the streaming fixture. Zero means
	// DefaultLargeFileSize. Tests that do not care about streaming should set
	// it small rather than skipping the file, so the tree shape stays the same.
	LargeFileSize int64
	// Seed varies the generated bytes. Zero means DefaultSeed.
	Seed uint64
}

// File is one generated file and everything the demo needs to assert about it.
type File struct {
	// Path is slash-separated and relative to the library root, which is what
	// identification parses and what the manifest can be compared against on
	// any host.
	Path string `json:"path"`
	Size int64  `json:"size"`
	// Hash is the BLAKE3 identity the CAS will arrive at (ADR-0005). The demo
	// asserts the catalog agrees rather than trusting that it does.
	Hash        string `json:"hash"`
	ContentType string `json:"content_type"`
	// Role is the asset role identification should land on, so the demo can
	// check that a subtitle beside a film did not become a film.
	Role string `json:"role"`
	// Ingestable reports whether the SCANNER will pick this file up.
	//
	// It is derived from ingest.MIMEForExtension — the same table the scanner
	// consults — rather than restated, because the demo's expected counts hang
	// off it and two lists that must agree is how they stop agreeing. A file
	// with an extension Heyarr does not recognise is skipped before
	// identification ever runs, which is why the deliberately unidentifiable
	// fixture never reaches ingest through a scan (see the note on that entry
	// in library()).
	Ingestable bool `json:"ingestable"`
}

// Manifest describes a generated library.
type Manifest struct {
	Root  string `json:"root"`
	Seed  uint64 `json:"seed"`
	Files []File `json:"files"`

	// DistinctBlobs is how many blobs a run that ingested EVERY file would end
	// up with. It is less than len(Files) exactly because of DuplicateHash.
	DistinctBlobs int `json:"distinct_blobs"`
	// IngestableFiles and IngestableBlobs are what a SCAN produces: the
	// scanner skips extensions the built-in table does not know, so these are
	// the numbers the acceptance demo asserts against.
	IngestableFiles int `json:"ingestable_files"`
	IngestableBlobs int `json:"ingestable_blobs"`
	// DuplicateHash is the hash deliberately shared by two files at different
	// paths — the case that must produce one blob and two assets (§13). It is
	// the single most valuable assertion in the demo, so the generator
	// guarantees it exists rather than hoping.
	DuplicateHash string `json:"duplicate_hash"`
	// LargestPath and LargestSize name the streaming fixture, so the range
	// assertions do not have to hardcode a filename.
	LargestPath string `json:"largest_path"`
	LargestSize int64  `json:"largest_size"`
}

// WriteJSON writes the manifest where a shell script can read it with jq.
func (m Manifest) WriteJSON(path string) error {
	f, err := os.Create(path) // #nosec G304 -- caller-chosen output path
	if err != nil {
		return fmt.Errorf("fixtures: creating manifest: %w", err)
	}
	defer func() { _ = f.Close() }()
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	if err := enc.Encode(m); err != nil {
		return fmt.Errorf("fixtures: writing manifest: %w", err)
	}
	return nil
}

// plan is one file to generate. Keeping the tree as data rather than as a
// sequence of writes is what lets the manifest and the filesystem be built from
// the same source — two lists that must agree is how they stop agreeing.
type plan struct {
	path        string
	contentType string
	role        string
	build       func(o Options) ([]byte, error)
	// large marks the streaming fixture, which is written in a stream rather
	// than built in memory.
	large bool
	// prefix is written before the streamed bytes, so a large fixture is still
	// the container its extension claims. Without it the streaming file is
	// named .mkv and identifies as "data", which is a fixture lying about
	// itself in exactly the place the range assertions look.
	prefix func() []byte
	// duplicateOf, when set, makes this file byte-identical to that path.
	duplicateOf string
}

// library is the tree. It covers every content type the naive identifier
// registers, both non-primary asset roles, a file nothing can parse, and two
// files that are byte-identical at different paths.
func library() []plan {
	return []plan{
		// Movies. The first is the streaming fixture.
		{
			path:        "movies/Blue Harvest (2019)/Blue Harvest (2019) - 2160p.mkv",
			contentType: "movie", role: "primary", large: true,
			prefix: func() []byte { return Matroska(nil) },
		},
		{
			path:        "movies/The Quiet Room (2001)/The Quiet Room (2001) - 1080p.mp4",
			contentType: "movie", role: "primary",
			build: func(Options) ([]byte, error) { return MP4([]byte(strings.Repeat("quiet ", 4096))), nil },
		},
		{
			path:        "movies/The Quiet Room (2001)/poster.jpg",
			contentType: "movie", role: "artwork",
			build: func(Options) ([]byte, error) { return JPEG("The Quiet Room (2001)"), nil },
		},
		// The pair that must collapse to one blob and stay two assets.
		{
			path:        "movies/Twice Told (2010)/Twice Told (2010) - 1080p.mp4",
			contentType: "movie", role: "primary",
			build: func(Options) ([]byte, error) { return MP4([]byte(strings.Repeat("twice ", 8192))), nil },
		},
		{
			path:        "movies/Told Twice (2011)/Told Twice (2011) - 1080p.mp4",
			contentType: "movie", role: "primary",
			duplicateOf: "movies/Twice Told (2010)/Twice Told (2010) - 1080p.mp4",
		},
		// Identification failure must never be ingest failure (M1-11) — but note
		// this file never gets the chance to prove that through a SCAN. The
		// scanner filters on extension before identification runs, and `.bin`
		// is not in the built-in table, so it is skipped. Reaching ingest with
		// something unidentifiable needs a producer that does not filter, which
		// is why #11 tests that path directly. It stays here because "the
		// scanner leaves junk alone" is itself worth asserting.
		{
			path:        "movies/____ nothing parses this ____.bin",
			contentType: "unknown", role: "primary",
			build: func(o Options) ([]byte, error) { return deterministicBytes(o.seed()+7, 4096), nil },
		},

		// Series, including a subtitle beside its episode.
		{
			path:        "tv/Night Shift/Season 01/S01E01 - Pilot.mkv",
			contentType: "series", role: "primary",
			build: func(Options) ([]byte, error) { return Matroska([]byte(strings.Repeat("pilot ", 4096))), nil },
		},
		{
			path:        "tv/Night Shift/Season 01/S01E01 - Pilot.en.srt",
			contentType: "series", role: "subtitle",
			build: func(Options) ([]byte, error) { return SRT(40), nil },
		},
		{
			path:        "tv/Night Shift/Season 01/S01E02 - Handover.mkv",
			contentType: "series", role: "primary",
			build: func(Options) ([]byte, error) { return Matroska([]byte(strings.Repeat("handover ", 4096))), nil },
		},

		// Music.
		{
			path:        "music/The Cartographers/Contour Lines (2001)/01 - Datum.flac",
			contentType: "music", role: "primary",
			build: func(Options) ([]byte, error) { return FLAC([]byte(strings.Repeat("datum ", 8192))), nil },
		},
		{
			path:        "music/The Cartographers/Contour Lines (2001)/02 - Benchmark.mp3",
			contentType: "music", role: "primary",
			build: func(Options) ([]byte, error) { return MP3(600), nil },
		},

		// Books.
		{
			path:        "books/Ada Prentice/The Long Survey.epub",
			contentType: "book", role: "primary",
			build: func(Options) ([]byte, error) { return EPUB("The Long Survey", "Ada Prentice", 6) },
		},
		{
			path:        "books/Ada Prentice/The Long Survey 001.cbz",
			contentType: "book", role: "primary",
			build: func(Options) ([]byte, error) { return CBZ("The Long Survey", 8) },
		},
	}
}

func (o Options) seed() uint64 {
	if o.Seed == 0 {
		return DefaultSeed
	}
	return o.Seed
}

func (o Options) largeSize() int64 {
	if o.LargeFileSize == 0 {
		return DefaultLargeFileSize
	}
	return o.LargeFileSize
}

// WriteLibrary generates the tree under root and reports what it built.
func WriteLibrary(root string, opts Options) (Manifest, error) {
	if root == "" {
		return Manifest{}, fmt.Errorf("fixtures: a root is required")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return Manifest{}, fmt.Errorf("fixtures: resolving %s: %w", root, err)
	}

	manifest := Manifest{Root: abs, Seed: opts.seed()}
	byPath := map[string]File{}
	seen := map[string]int{}

	for _, p := range library() {
		full := filepath.Join(abs, filepath.FromSlash(p.path))
		if err := os.MkdirAll(filepath.Dir(full), 0o750); err != nil {
			return Manifest{}, fmt.Errorf("fixtures: creating %s: %w", filepath.Dir(full), err)
		}

		var (
			size int64
			hash hashing.Hash
		)
		switch {
		case p.large:
			var prefix []byte
			if p.prefix != nil {
				prefix = p.prefix()
			}
			size, hash, err = writeStream(full, prefix, opts.seed(), opts.largeSize())
		case p.duplicateOf != "":
			source, ok := byPath[p.duplicateOf]
			if !ok {
				return Manifest{}, fmt.Errorf("fixtures: %s duplicates %s, which has not been written yet",
					p.path, p.duplicateOf)
			}
			err = copyFile(filepath.Join(abs, filepath.FromSlash(p.duplicateOf)), full)
			size, hash = source.Size, hashing.MustParse(source.Hash)
		default:
			var body []byte
			if body, err = p.build(opts); err == nil {
				size, hash, err = writeBytes(full, body)
			}
		}
		if err != nil {
			return Manifest{}, fmt.Errorf("fixtures: writing %s: %w", p.path, err)
		}

		f := File{
			Path: p.path, Size: size, Hash: hash.String(),
			ContentType: p.contentType, Role: p.role,
			Ingestable: ingest.MIMEForExtension(ingest.Ext(ingest.Base(p.path))) != "",
		}
		byPath[p.path] = f
		manifest.Files = append(manifest.Files, f)
		seen[f.Hash]++

		if size > manifest.LargestSize {
			manifest.LargestPath, manifest.LargestSize = p.path, size
		}
		if p.duplicateOf != "" {
			manifest.DuplicateHash = f.Hash
		}
	}

	manifest.DistinctBlobs = len(seen)

	ingestable := map[string]struct{}{}
	for _, f := range manifest.Files {
		if !f.Ingestable {
			continue
		}
		manifest.IngestableFiles++
		ingestable[f.Hash] = struct{}{}
	}
	manifest.IngestableBlobs = len(ingestable)

	// The duplicate pair is the demo's most valuable assertion, so verify the
	// generator actually produced it rather than trusting the plan. A fixture
	// tree that quietly stopped containing the case it exists for would make
	// the demo pass while testing nothing.
	if manifest.DuplicateHash == "" {
		return Manifest{}, fmt.Errorf("fixtures: no duplicate pair was generated")
	}
	if n := seen[manifest.DuplicateHash]; n != 2 {
		return Manifest{}, fmt.Errorf("fixtures: the duplicate hash appears %d times, want exactly 2", n)
	}
	if manifest.DistinctBlobs != len(manifest.Files)-1 {
		return Manifest{}, fmt.Errorf("fixtures: %d files produced %d distinct blobs, want %d — "+
			"an unintended collision would make the dedup assertion meaningless",
			len(manifest.Files), manifest.DistinctBlobs, len(manifest.Files)-1)
	}
	return manifest, nil
}

// filePerm matches what a real media library looks like: readable by the owner
// and the group that owns the mount (§74's service account and group model).
// 0600 would be tighter and wrong — the fixture exists to stand in for content
// Heyarr finds on disk, and ingest's permission handling should meet the same
// mode in the demo as it will in production.
const filePerm = 0o640

func writeBytes(path string, body []byte) (int64, hashing.Hash, error) {
	if err := os.WriteFile(path, body, filePerm); err != nil { // #nosec G306 -- see filePerm
		return 0, hashing.Hash{}, err
	}
	hasher := hashing.New()
	if _, err := hasher.Write(body); err != nil {
		return 0, hashing.Hash{}, err
	}
	return int64(len(body)), hasher.Sum(), nil
}

// writeStream generates a large file without ever holding it in memory. The
// point of the streaming fixture is that nothing buffers it, and a generator
// that built it in a []byte would be the first thing to break that.
func writeStream(path string, prefix []byte, seed uint64, size int64) (int64, hashing.Hash, error) {
	f, err := os.Create(path) // #nosec G304 -- generated path under the caller's root
	if err != nil {
		return 0, hashing.Hash{}, err
	}
	defer func() { _ = f.Close() }()

	hasher := hashing.New()
	sink := io.MultiWriter(f, hasher)

	var written int64
	if len(prefix) > 0 {
		n, werr := sink.Write(prefix)
		if werr != nil {
			return 0, hashing.Hash{}, werr
		}
		written += int64(n)
		size -= int64(n)
	}

	streamed, err := io.Copy(sink, &prng{state: seed, remaining: size})
	if err != nil {
		return 0, hashing.Hash{}, err
	}
	written += streamed
	if err := f.Sync(); err != nil {
		return 0, hashing.Hash{}, err
	}
	return written, hasher.Sum(), nil
}

func copyFile(src, dst string) error {
	body, err := os.ReadFile(src) // #nosec G304 -- generated path under the caller's root
	if err != nil {
		return err
	}
	// #nosec G306,G703 -- see filePerm; both paths are built from the compile-time
	// plan in library(), joined under a root the caller chose, and never from input.
	return os.WriteFile(dst, body, filePerm)
}

// prng is a seeded, incompressible byte source. Incompressible matters: a
// filesystem with transparent compression would otherwise make a 200 MB fixture
// cost nothing, and the streaming assertions would be measuring a much smaller
// file than they claim.
type prng struct {
	state     uint64
	remaining int64
}

func (p *prng) Read(b []byte) (int, error) {
	if p.remaining <= 0 {
		return 0, io.EOF
	}
	if int64(len(b)) > p.remaining {
		b = b[:p.remaining]
	}
	for i := range b {
		p.state = p.state*6364136223846793005 + 1442695040888963407
		b[i] = byte(p.state >> 33 & 0xFF)
	}
	p.remaining -= int64(len(b))
	return len(b), nil
}

func deterministicBytes(seed uint64, n int) []byte {
	out := make([]byte, n)
	p := &prng{state: seed, remaining: int64(n)}
	_, _ = io.ReadFull(p, out)
	return out
}

func crc32Of(b []byte) uint32 { return crc32.ChecksumIEEE(b) }

func escapeXML(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&apos;")
	return r.Replace(s)
}

func slug(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

// Dir is the conventional name of the generated library within a work
// directory, so the demo and the tests agree without passing it around.
func Dir(work string) string { return path.Join(work, "library") }
